// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuWlVM__P9whHEqCvXwIRAci060V5M2Dg',
    appId: '1:378817763502:web:096acb6272e18d2812353f',
    messagingSenderId: '378817763502',
    projectId: 'otomoto-1533c',
    authDomain: 'otomoto-1533c.firebaseapp.com',
    storageBucket: 'otomoto-1533c.firebasestorage.app',
    measurementId: 'G-02CF5Y50MY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuWlVM__P9whHEqCvXwIRAci060V5M2Dg',
    appId: '1:378817763502:web:cec1ec8536c8fc4b12353f',
    messagingSenderId: '378817763502',
    projectId: 'otomoto-1533c',
    authDomain: 'otomoto-1533c.firebaseapp.com',
    storageBucket: 'otomoto-1533c.firebasestorage.app',
    measurementId: 'G-2G1YXFKVD8',
  );
}
