// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf0csg4CIW0KgWHpYqx5dmviF-2MEvFgU',
    appId: '1:1004725264440:web:bac96461cbe527c1ed86cd',
    messagingSenderId: '1004725264440',
    projectId: 'otomoto-840f7',
    authDomain: 'otomoto-840f7.firebaseapp.com',
    storageBucket: 'otomoto-840f7.firebasestorage.app',
    measurementId: 'G-EEE7EDH1PL',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf0csg4CIW0KgWHpYqx5dmviF-2MEvFgU',
    appId: '1:1004725264440:web:97ab6359749f4b70ed86cd',
    messagingSenderId: '1004725264440',
    projectId: 'otomoto-840f7',
    authDomain: 'otomoto-840f7.firebaseapp.com',
    storageBucket: 'otomoto-840f7.firebasestorage.app',
    measurementId: 'G-XLRKDSCR2Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcSFOYH5PjIh18g0tl0oWGCs4-8C8oii8',
    appId: '1:1004725264440:ios:1919828c97b20591ed86cd',
    messagingSenderId: '1004725264440',
    projectId: 'otomoto-840f7',
    storageBucket: 'otomoto-840f7.firebasestorage.app',
    iosBundleId: 'com.example.otomoto',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSFOYH5PjIh18g0tl0oWGCs4-8C8oii8',
    appId: '1:1004725264440:ios:1919828c97b20591ed86cd',
    messagingSenderId: '1004725264440',
    projectId: 'otomoto-840f7',
    storageBucket: 'otomoto-840f7.firebasestorage.app',
    iosBundleId: 'com.example.otomoto',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpa3hYzIrmOMqV7boufCNgLFd6QJAW8U',
    appId: '1:1004725264440:android:fb6178885f1f4e48ed86cd',
    messagingSenderId: '1004725264440',
    projectId: 'otomoto-840f7',
    storageBucket: 'otomoto-840f7.firebasestorage.app',
  );

}